# Generated by Django 5.2.1 on 2025-05-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('description', models.TextField(verbose_name='Описание фильма')),
                ('review', models.TextField(verbose_name='Отзыв о фильме')),
            ],
            options={
                'verbose_name': 'Отзыв о фильме',
                'verbose_name_plural': 'Отзывы о фильмах',
            },
        ),
    ]
